language: php

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - composer config discard-changes true
  - composer validate --no-check-all --strict
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest
  - travis_retry composer require --dev satooshi/php-coveralls

script:
  - composer run phpunit -- --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v